title: Josh learns system programming

author:
  name: Josh Toye
  email: by.josht@gmail.com

description: >
  A blog to document my systems programming learning journey.

remote_theme: "jekyll/minima@1e8a445"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  hide_site_feed_link: true