title: Your awesome title

author:
  name: Josh Toye
  email: by.josht@gmail.com

description: >
  A blog to document my systems programming learning journey.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark
  
